# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程类名')),
                ('desc', models.CharField(max_length=300, verbose_name='类别简介')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '课程类别',
                'verbose_name': '课程类别',
            },
        ),
        migrations.CreateModel(
            name='ExamLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='考试科目')),
                ('desc', models.CharField(max_length=300, verbose_name='科目描述')),
                ('degree',
                 models.CharField(
                     choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=2, verbose_name='科目难度')),
                ('students', models.IntegerField(default=0, verbose_name='考试人数')),
                ('image', models.ImageField(upload_to='image/%Y/%M', verbose_name='考试封面')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('exam_times', models.IntegerField(default=0, verbose_name='考试时长时长（分钟数）')),
                ('examcategory',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to='examination.ExamCategory',
                     verbose_name='课程类名')),
            ],
            options={
                'verbose_name_plural': '考试科目',
                'verbose_name': '考试科目',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('examcategory',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE, to='examination.ExamCategory', verbose_name='课程类名')),
                ('examlesson',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE, to='examination.ExamLesson', verbose_name='考试科目')),
            ],
            options={
                'verbose_name_plural': '试题列表',
                'verbose_name': '试题列表',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('xz', '选择题'), ('pd', '判断题')], max_length=2)),
                ('content', models.TextField(verbose_name='题目内容')),
                ('OptionA', models.TextField(blank=True, verbose_name='A选项字段')),
                ('OptionB', models.TextField(blank=True, verbose_name='B选项字段')),
                ('OptionC', models.TextField(blank=True, verbose_name='C选项字段')),
                ('OptionD', models.TextField(blank=True, verbose_name='D选项字段')),
                ('answer', models.CharField(max_length=50, verbose_name='正确答案')),
                ('boolt', models.TextField(default='正确', verbose_name='判断题正确')),
                ('boolf', models.TextField(default='错误', verbose_name='判断题错误')),
                ('score', models.IntegerField(default=0, verbose_name='本题分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('examcategory',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to='examination.ExamCategory',
                     verbose_name='课程类名')),
            ],
            options={
                'verbose_name_plural': '题库',
                'verbose_name': '题库',
            },
        ),
        migrations.AddField(
            model_name='exampaper',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='examination.Question', verbose_name='题目'),
        ),
    ]
