# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='u姓名')),
                ('number_id', models.IntegerField(blank=True, null=True, verbose_name='试卷编号')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime, null=True, verbose_name='开始时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='exampaper',
            name='question',
        ),
        migrations.AddField(
            model_name='exampaper',
            name='examFile',
            field=models.FileField(default='/file/', upload_to='file/', verbose_name='考试试卷文件'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='examLessonNum',
            field=models.IntegerField(default=1, verbose_name='试卷编号'),
        ),
        migrations.AddField(
            model_name='question',
            name='examLessonNum',
            field=models.IntegerField(default=1, verbose_name='试卷编号'),
        ),
    ]
