# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='question',
        ),
        migrations.AddField(
            model_name='exampaper',
            name='examFile',
            field=models.FileField(default='/file/', upload_to='file/', verbose_name='考试试卷文件'),
        ),
        migrations.AddField(
            model_name='question',
            name='examLessonNum',
            field=models.IntegerField(default=1, verbose_name='试卷编号'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionNum',
            field=models.IntegerField(default=1, verbose_name='题目编号'),
        ),
    ]
