# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20180607_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='examFile',
            field=models.FileField(default='/file/', upload_to='file/', verbose_name='考试试卷文件'),
        ),
    ]
