# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_exampaper_examlessonnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionNum',
        ),
    ]
