# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_auto_20180809_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='start_time',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='开始时间'),
        ),
    ]
