# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_remove_question_questionnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('number_id', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='试卷编号')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 10, 58, 36, 437352), verbose_name='开始时间')),
            ],
        ),
    ]
