# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0007_answercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间'),
        ),
    ]
