# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_auto_20180808_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='u姓名'),
        ),
    ]
