# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_auto_20180808_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='add_time',
            field=models.DateTimeField(default=None, verbose_name='添加时间'),
        ),
    ]
