# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_auto_20180809_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='开始时间'),
        ),
    ]
