# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0011_auto_20180808_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='start_time',
            field=models.DateTimeField(default=(2018, 8, 8, 17, 13, 32, 2, 220, 0), verbose_name='开始时间'),
        ),
    ]
