# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0017_auto_20180808_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
