# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0026_auto_20180808_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='start_time',
            field=models.BinaryField(blank=True, default=datetime.datetime.now, null=True, verbose_name='开始时间'),
        ),
    ]
