# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0027_auto_20180808_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='number_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='试卷编号'),
        ),
    ]
