# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0028_auto_20180808_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercard',
            name='start_time',
            field=models.BinaryField(blank=True, default=0.0, null=True, verbose_name='开始时间'),
        ),
    ]
