# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='coursecategory',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
