# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='InstanceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='实例名')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('instanceID', models.CharField(max_length=100, verbose_name='实例ID')),
                ('instanceST', models.CharField(max_length=50, verbose_name='实例状态')),
                ('labID', models.IntegerField(default=0, verbose_name='实验ID')),
                ('labName', models.CharField(max_length=50, verbose_name='实验名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '活跃实例',
                'verbose_name': '活跃实例',
            },
        ),
    ]
