# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180807_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexamination',
            name='frist_time',
        ),
    ]
