# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userexamination_frist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamination',
            name='frist_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 1, 1, 1, 1), verbose_name='第一次添加时间'),
        ),
    ]
